---
exp_name: cora
exp_dir: exp/cora
runner: CitationRunner
use_gpu: true
gpus: [0]
seed: 1234
dataset:
  name: Cora  
  path: data/citation
  rand_split: true
  train_ratio: 0.01
  label_size: 7
model:
  name: GNN
  feat_dim: 64
  hidden_dim: 64
  output_dim: 7
  num_layer: 1
  num_prop: 100
  num_edge_type: 1
  aggregate_type: sum
  update_func: GRU
  output_func: MLP
  # grad_method: Neumann_RBP
  # grad_method: CG_RBP
  # grad_method: RBP
  # grad_method: TBPTT
  grad_method: BPTT
  truncate_iter: 5
train:
  optimizer: SGD
  lr_decay: 0.1
  lr_decay_steps: [10000]
  num_workers: 0
  max_epoch: 2000
  batch_size: 1
  display_iter: 10
  snapshot_epoch: 1000
  valid_epoch: 20
  lr: 1.0e-3
  wd: 5.0e-4
  momentum: 0.9
  shuffle: true
  is_resume: false
  resume_model: None